// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASMd4vuk1xyNH_Dd3Tx60j8DxJBBik3wQ',
    appId: '1:182786825095:web:56b1f468c41247d297d122',
    messagingSenderId: '182786825095',
    projectId: 'tracking-app-919',
    authDomain: 'tracking-app-919.firebaseapp.com',
    storageBucket: 'tracking-app-919.firebasestorage.app',
    measurementId: 'G-2EL1E39J52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9W3eV08K9ENMgxmzOPJkM90oQEGIULas',
    appId: '1:182786825095:android:28ae2ca948b2ab0b97d122',
    messagingSenderId: '182786825095',
    projectId: 'tracking-app-919',
    storageBucket: 'tracking-app-919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx3ndOutynHTSI_wbJN64pq28dlpmStL0',
    appId: '1:182786825095:ios:1079e1742041eb3e97d122',
    messagingSenderId: '182786825095',
    projectId: 'tracking-app-919',
    storageBucket: 'tracking-app-919.firebasestorage.app',
    iosBundleId: 'com.example.appName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx3ndOutynHTSI_wbJN64pq28dlpmStL0',
    appId: '1:182786825095:ios:1079e1742041eb3e97d122',
    messagingSenderId: '182786825095',
    projectId: 'tracking-app-919',
    storageBucket: 'tracking-app-919.firebasestorage.app',
    iosBundleId: 'com.example.appName',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASMd4vuk1xyNH_Dd3Tx60j8DxJBBik3wQ',
    appId: '1:182786825095:web:2d49d1cc55789ca397d122',
    messagingSenderId: '182786825095',
    projectId: 'tracking-app-919',
    authDomain: 'tracking-app-919.firebaseapp.com',
    storageBucket: 'tracking-app-919.firebasestorage.app',
    measurementId: 'G-NV0B4VDE8E',
  );
}
